### PR TITLE
Add example programs for reading nginx logs.

### PR DESCRIPTION
**Pull request by mstemm**
Add example programs and docker-compose files that show how to read
nginx logs using logstash, save the parsed results in elasticsearch,
and summarize the parsed results in juttle programs.

I am checking the programs in, but I'm not including them in the
examples README or providing a standalong README for now, as the
program seems pretty specific to our situation. Maybe we need another
repository/location just for internal-facing programs and supporting
infrastructure?

@demmer @philrz @davidvgalbraith

### CODE REVIEW

**Comment by dmehra** [comment]
I could use a README here, is the idea that you start up logstash to point at your own nginx so its logs go into the elasticsearch inside the container? I.e. you have to run it for a while before the juttle program will pick up any data?

(And generally if we are committing this to juttle-engine, i think it should have a README explaining what it's for, maybe starting with "Internal example")

**Comment by mstemm** [comment]
That's right, logstash parses /var/log/nginx/access.log and saves the results in elasticsearch. I've configured logstash to read the entire file on startup, so you don't actually have to wait that long (assuming you've gotten traffic in the past).

**Comment by dmehra** [comment]
Ok please add a README.

**Comment by mstemm** [comment]
@dmehra look again?

**Comment by mstemm** [comment]
Added a README, merging so I can include in upcoming juttle-engine release.

**Pull request merged**
