### PR TITLE
Updating versions.

### PR DESCRIPTION
**Pull request by mstemm**
Update graphite/influx/juttle-viewer to reflect versions listed on
https://github.com/juttle/juttle-engine/issues/77.

If tests go well, we'll publish official releases of any rcs, check again, and then merge.

### CODE REVIEW

**Comment by mnibecker** [comment]
@mstemm talked with @rlgomes about failure. Decided to skip test and go ahead with release.

**Comment by mnibecker** [comment]
+1

**Comment by demmer** [comment]
I just rebased and bumped the elastic adapter version.

**Comment by demmer** [comment]
Travis failure was something unrelated (passed on node 4.2). Merging and publishing the release.

**Pull request merged**
