### PR TITLE
Update docker

### PR DESCRIPTION
**Pull request by mstemm**
Update all the Dockerfiles/READMEs/docker-compose files to refer to juttle-engine instead of outrigger. I pushed juttle-engine 0.2.2 to docker hub and these programs now all mostly work.

There are some remaining bugs, though:
 - For some programs with barcharts, there's a warning related to promises and the barchart isn't rerendering (juttle/juttle-viz#53).
 - When reading from postgres, you can't specify a -timeField without also specifying a -from/-to (juttle/juttle-sql-adapter-common#42)
 - Some errors are making it to the browser but not being displayed in the viewer (juttle/juttle-viewer#15).

@dmehra @VladVega @go-oleg

### CODE REVIEW

**Comment by dmehra** [comment]
I just tried running all containers (with the cover-all `docker compose`), and the cadvisor/influx one is having some trouble, cadvisor is failing to write stats even though influx appears to be up:

```
cadvisor_1             | E0214 19:39:46.808432 00001 memory.go:90] failed to write stats to influxDb - Server returned (404): 404 page not found
cadvisor_1             | E0214 19:39:48.808501 00001 memory.go:90] failed to write stats to influxDb - Server returned (404): 404 page not found
cadvisor_1             | E0214 19:39:50.818165 00001 memory.go:90] failed to write stats to influxDb - Server returned (404): 404 page not found
cadvisor_1             | E0214 19:39:53.098615 00001 memory.go:90] failed to write stats to influxDb - Server returned (404): 404 page not found
cadvisor_1             | E0214 19:39:55.107951 00001 memory.go:90] failed to write stats to influxDb - Server returned (404): 404 page not found
influxdb_1             | [wal] 2016/02/14 19:39:55 Flush due to idle. Flushing 7 series with 7 points and 434 bytes from partition 1
influxdb_1             | [wal] 2016/02/14 19:39:55 write to index of partition 1 took 4.224993ms
```

**Comment by dmehra** [comment]
And the postgres demo produces no output. I'll debug that one, and leave the cadvisor issue to you @mstemm

**Comment by rlgomes** [comment]
+1 looks good!

**Comment by mstemm** [comment]
For cadvisor, make sure you've deleted all images in your docker install. It's very possible you have an old cadvisor lying around--remember that docker run doesn't repull the latest version of a container.

For postgres, I haven't pushed any new juttle-engine yet. I'm waiting for this to be on the mainline first.

**Pull request merged**
