### PR TITLE
add all adapters

### PR DESCRIPTION
**Pull request by demmer**
Include all currently supported adapters as part of the package dependencies.

### CODE REVIEW

**Comment by demmer** [comment]
@mstemm

**Comment by mstemm** [comment]
According to https://github.com/juttle/juttle/issues/305, opentsdb is 0.1.2 and sqlite is 0.3.0.

**Comment by demmer** [comment]
The opentsdb dependency is fine as-is since the only change from 0.1.1 to 0.1.2 was how we run juttle in travis. For sqlite it looks like 0.3.1 contains a bugfix so there's no reason to not pull that one in as well.

Still we should be consistent -- @VladVega can you update the versions in juttle/juttle#305?

**Comment by VladVega** [comment]
@demmer changed sqlite to 0.3.1 in the issue.

**Comment by demmer** [comment]
OK I'm merging this now.

**Pull request merged**
