### PR TITLE
Adding tutorial juttles and docker config

### PR DESCRIPTION
**Pull request by dmehra**
This adds the juttle programs, docker container config, and image config for the data volume, for the GitHub-based tutorial, see README.md. 

The data volume is already published to docker, as `juttle/elastic_github_data`. 

I had to make changes to the elastic_news juttles to `read elastic -id 'news'` because their instance of elastic adapter is no longer the default; I made the tutorial instance default (top in the list) so tutorial programs can simply do `read elastic` without extra complexity.

The tutorial itself is coming in a PR in juttle repo. I'll want to get this merged first, deployed to demo.juttle.io, then merge the tutorial text, and publish it to github pages (docs site), because it will have follow-along links to demo.juttle.io.

@mstemm @demmer

### CODE REVIEW

**Comment by mstemm** [comment]
the changes look good to me. I mentioned in the juttle PR that the source files are in both repos, while I think they should only be in juttle-engine.

**Comment by mstemm** [comment]
I'd also suggest adding a link to the tutorial from the top level README. I know there's also a link from the juttle README, but I suspect juttle-engine will be a popular landing site for new users so a tutorial link here would be useful.

**Comment by dmehra** [comment]
@mstemm, README change ok?

**Comment by mstemm** [comment]
lgtm.

**Pull request merged**
