### PR TITLE
Adding links from example README to demo.juttle.io

### PR DESCRIPTION
**Pull request by dmehra**
@mstemm - added links for better discovery of demo.juttle.io examples.
I also intend to add the same links from each adapter's README.

### CODE REVIEW

**Comment by mstemm** [comment]
Instead of having nearly identical text for each of the subdirectory READMEs, maybe you could just add demo.juttle.io links to the table of the top level README?

**Comment by dmehra** [comment]
How about I do that in addition, not instead. Who knows how people will navigate the examples tree, I can imagine them heading directly to the README of the thing they are interested in.

**Comment by mstemm** [comment]
I guess so. I never thought of the subdirectory READMEs as standalone documents that could be read on their own, though.

**Comment by mstemm** [comment]
If you keep the subdirectory text, can you move it into the Juttle Programs section? Something like "you can also view these programs at demo.juttle.io".

**Comment by dmehra** [comment]
You know, if viewing the individual READMEs as potentially standalone, I can see how they are missing something. Let's keep the line up top in Setup but rephrase as "You can view this example on the demo system (link) or run it on your own using docker (see the parent README (link)).".

**Comment by dmehra** [comment]
@mstemm ok now?

**Comment by mstemm** [comment]
I'd still vote for moving the subdirectory demo text closer to the description of programs, but I'll defer to you if you want to keep it the way it is.

Also the demo column of the table seems kinda ugly, but I can't think of anything better.

lgtm.

**Comment by dmehra** [comment]
Can't think of anything better either, so merging.

**Pull request merged**
