### PR TITLE
just using this branch to see how things behave in travis

### LINKED ISSUE #31: intermittent test failure due to page crashes during app tests
we're seeing this periodically like so:

https://travis-ci.org/juttle/juttle-engine/jobs/108682020

### PR DESCRIPTION
**Pull request by rlgomes**
fixes #31

this is much of a fix really as we're turning on debug logging for
juttle-engine so we can catch issues better when they happen and also
making sure to simply startup a clean juttle-engine and browser session
for each test which seems to have made things more stable.

### CODE REVIEW

**Comment by rlgomes** [comment]
@demmer turned on debug logging and not seeing the issue in travis... damn it!

**Comment by rlgomes** [comment]
Ok removed all of that fiddling and now pushed a simple change to not rely on the `ready` callback and instead check the port is listening before proceeding.

**Comment by rlgomes** [comment]
Will merge on green as to get more coverage by others running this on their branches and still need to see about getting more debug logs from the browser session itself. We may need to consider 1) using open sauce which increases our external dependencies for running tests or 2) push logs + artifacts (ie add screenshooting to tests) to somewhere so its easy to debug failed runs. Thinking maybe we could push such artifacts to a github repo dedicated solely to this ? which could keep simply 1 weeks worth of data and at the end of each week we'd remove all of the older artifacts ?

**Comment by dmehra** [comment]
Pretty sure Travis has a native way to archive to s3, to unique paths if the filename in the bucket includes timestamp, or one latest artifact being overwritten (I was thinking to keep one code coverage report for each repo in that way).

**Comment by rlgomes** [comment]
@dmehra but s3 will require some way to browser it as you well remember from a previous experience.

**Comment by rlgomes** [comment]
I'd be more inclined to use (or abuse to be more correct) a github repo which is eaiser to browse

**Comment by dmehra** [comment]
If the Travis log has the s3 link that would be sufficient - in a public bucket, you'd just download the artifact on click.

This documents how to upload to s3: https://docs.travis-ci.com/user/uploading-artifacts/

The other thing people do is apparently pushing to gh-pages branch of the repo (where we publish docs for juttle and juttle-viz) so browsing is handled.

**Comment by rlgomes** [comment]
@dmehra the idea was to push to the gh-pages of an artifacts repo...

**Comment by rlgomes** [comment]
closing this in favor of an upcoming PR to easily run the tests locally in docker by setting a flag as this is how I uncovered the issue to begin with.

**Pull request closed without merging**
